### ISSUE TITLE
segfault error with dtw method

### ISSUE THREAD

**Issue by hichew22** [philips-software/latrend#159]
Hello,

I am trying to use the dtw method as follows. I have a large dataframe consisting of longitudinal Y values (1 value per day, 31 values per individual, and ~700 individuals).

```
dtw_method <-
  lcMethodDtwclust(response = "Y",
                   nClusters = 4,
                   nbRedrawing = 1)
dtw_method

dtw_model <- latrend(dtw_method, data = df)
```

However, when I try to call the last line, I get an error saying that R has encountered a fatal error and the session must be terminated. When I try to knit my Rmd, I encounter a very long error message:
![image](https://github.com/philips-software/latrend/assets/137368713/4b2e5f39-8c9b-4883-a7b8-3442ea2a341b)

Could you let me know how to fix this?

Thank you!

**Comment by niekdt** [comment]
This may be an issue with how latrend prepares the data for the dtwclust package, or a bug in dtwclust triggered by your data.

Quickest way to identify where the problem lies is by directly using the dtwclust package. See `dtwclust::tsclust`
Please let me know if this works.

**Comment by niekdt** [comment]
`tsmatrix` is for repeated measures data of equal length, hence the introduction of NAs for some of the series.

dtwclust can handle series of unequal length if you pass them as a list of time series vectors. In a previous edited post I noticed a warning about `lapply(series, as.numeric)` on coercion introducing NAs, which would suggest that the method of splitting the time series into a list of series is creating vectors of mixed types (e.g. numbers and characters).

To test this, you can run:
`all(sapply(series, is.numeric))`

Since this is an issue related to the dtwclust package, the contributors of that package will be better able to help you.

**Comment by niekdt** [comment]
If I'm understanding correctly, when knitting, you get the segfault error also when directly using `dtwclust::tsclust`? This would suggest it's not an issue with latrend.

In general, I've noticed that knitr can sometimes produce some really unexplainable behavior, things like forgetting R options, which could lead to errors in latrend calls. But that does not seem to be the problem here.

Since the error you posted is triggered by the `sys.getenv` default-option call, setting the RCPP_PARALLEL_NUM_THREADS environment variable may prevent the problematic function from being called. Worth a try, although it's likely a symptom of another underlying issue.
Might also want to look in the dtwclust documentation to see if there are ways to disable parallel computation.
