### ISSUE TITLE
Any plan to add parallel computing when fitting models?

### ISSUE THREAD

**Issue by conge** [philips-software/latrend#21]
First of all, thank you very much for making trajectory analysis simpler with this great package! Great work.

I was wondering if you have any plan to implement parallel computing for model fitting (e.g when using latrendBatch() ). It is painful to see the package only uses one CPU knowing there are 10 available.

Thanks,

Yang

**Comment by niekdt** [comment]
Dear Yang,

Great suggestion. It has not been a priority so far, but I did take this into account when implementing the latrend fitting functions, so it should be a relatively trivial change.

Do you have any recommendations on the most suitable cross-platform package/mechanism to enable parallel computation?
I quite like the `foreach` package as it supports several parallel back-ends.

In that case, I suspect it is preferable to have an argument `.parallel = TRUE` for the `latrend*()` functions, as some of the underlying cluster packages might make use of %dopar% as well. That could result in nested parallelization with unnecessary overhead.

Feel free to implement this and submit a PR. Alternatively, I can find some time to implement this in the coming 2 weeks.

Best regards,
Niek

**Comment by niekdt** [comment]
It was not quite the trivial change I was expecting it to be, but it should be working now. 

The main trap for users, as it took me a while to notice, is that custom S4 classes and methods need to be loaded onto the cluster workers on Windows. I've added checks for this to the methods, as this otherwise leads to unexpected results.
